/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface BondAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bonds"
      | "cancelBond"
      | "claim"
      | "claimCollateral"
      | "claimRefund"
      | "closeBond"
      | "complianceAccess"
      | "createBond"
      | "getBidCount"
      | "getBidder"
      | "getBond"
      | "getEncryptedRate"
      | "getWinners"
      | "hasBid"
      | "isWinner"
      | "liquidate"
      | "nextBondId"
      | "publishResults"
      | "repay"
      | "resolvePass"
      | "revealForCompliance"
      | "settle"
      | "submitRate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondCancelled"
      | "BondClosed"
      | "BondCreated"
      | "BondLiquidated"
      | "BondRepaid"
      | "BondResolved"
      | "BondSettled"
      | "ComplianceAccessGranted"
      | "LenderClaimed"
      | "PassResolved"
      | "RateBidSubmitted"
      | "RefundClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bonds", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimCollateral",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createBond",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBidder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWinner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBondId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publishResults",
    values: [BigNumberish, BigNumberish, BytesLike, boolean[], BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "resolvePass",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealForCompliance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRate",
    values: [BigNumberish, InEuint64Struct]
  ): string;

  decodeFunctionResult(functionFragment: "bonds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "complianceAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBidCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBidder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextBondId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolvePass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealForCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitRate", data: BytesLike): Result;
}

export namespace BondCancelledEvent {
  export type InputTuple = [bondId: BigNumberish, reason: string];
  export type OutputTuple = [bondId: bigint, reason: string];
  export interface OutputObject {
    bondId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondClosedEvent {
  export type InputTuple = [bondId: BigNumberish, cancelled: boolean];
  export type OutputTuple = [bondId: bigint, cancelled: boolean];
  export interface OutputObject {
    bondId: bigint;
    cancelled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondCreatedEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    borrower: AddressLike,
    collateralAmount: BigNumberish,
    totalBorrow: BigNumberish,
    slotCount: BigNumberish,
    maxRate: BigNumberish,
    duration: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    bondId: bigint,
    borrower: string,
    collateralAmount: bigint,
    totalBorrow: bigint,
    slotCount: bigint,
    maxRate: bigint,
    duration: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    bondId: bigint;
    borrower: string;
    collateralAmount: bigint;
    totalBorrow: bigint;
    slotCount: bigint;
    maxRate: bigint;
    duration: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondLiquidatedEvent {
  export type InputTuple = [bondId: BigNumberish];
  export type OutputTuple = [bondId: bigint];
  export interface OutputObject {
    bondId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondRepaidEvent {
  export type InputTuple = [bondId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [bondId: bigint, amount: bigint];
  export interface OutputObject {
    bondId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondResolvedEvent {
  export type InputTuple = [bondId: BigNumberish];
  export type OutputTuple = [bondId: bigint];
  export interface OutputObject {
    bondId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondSettledEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    clearingRate: BigNumberish,
    totalRepayment: BigNumberish
  ];
  export type OutputTuple = [
    bondId: bigint,
    clearingRate: bigint,
    totalRepayment: bigint
  ];
  export interface OutputObject {
    bondId: bigint;
    clearingRate: bigint;
    totalRepayment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceAccessGrantedEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    granter: AddressLike,
    regulator: AddressLike
  ];
  export type OutputTuple = [
    bondId: bigint,
    granter: string,
    regulator: string
  ];
  export interface OutputObject {
    bondId: bigint;
    granter: string;
    regulator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LenderClaimedEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    lender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bondId: bigint, lender: string, amount: bigint];
  export interface OutputObject {
    bondId: bigint;
    lender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PassResolvedEvent {
  export type InputTuple = [bondId: BigNumberish, pass: BigNumberish];
  export type OutputTuple = [bondId: bigint, pass: bigint];
  export interface OutputObject {
    bondId: bigint;
    pass: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateBidSubmittedEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    bidIndex: BigNumberish,
    lender: AddressLike
  ];
  export type OutputTuple = [bondId: bigint, bidIndex: bigint, lender: string];
  export interface OutputObject {
    bondId: bigint;
    bidIndex: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    bondId: BigNumberish,
    lender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bondId: bigint, lender: string, amount: bigint];
  export interface OutputObject {
    bondId: bigint;
    lender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BondAuction extends BaseContract {
  connect(runner?: ContractRunner | null): BondAuction;
  waitForDeployment(): Promise<this>;

  interface: BondAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bonds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        borrower: string;
        collateralToken: string;
        collateralAmount: bigint;
        borrowToken: string;
        slotSize: bigint;
        slotCount: bigint;
        maxRate: bigint;
        duration: bigint;
        biddingDeadline: bigint;
        maturity: bigint;
        minBidders: bigint;
        state: bigint;
        bidCount: bigint;
        currentPass: bigint;
        clearingRate: string;
        settledRate: bigint;
        totalRepayment: bigint;
      }
    ],
    "view"
  >;

  cancelBond: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  claim: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  claimCollateral: TypedContractMethod<
    [bondId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [bondId: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeBond: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  complianceAccess: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  createBond: TypedContractMethod<
    [
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      borrowToken: AddressLike,
      slotSize: BigNumberish,
      slotCount: BigNumberish,
      maxRate: BigNumberish,
      duration: BigNumberish,
      biddingDuration: BigNumberish,
      minBidders: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getBidCount: TypedContractMethod<[bondId: BigNumberish], [bigint], "view">;

  getBidder: TypedContractMethod<
    [bondId: BigNumberish, bidIndex: BigNumberish],
    [string],
    "view"
  >;

  getBond: TypedContractMethod<
    [bondId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        collateralToken: string;
        collateralAmount: bigint;
        borrowToken: string;
        slotSize: bigint;
        slotCount: bigint;
        maxRate: bigint;
        duration: bigint;
        biddingDeadline: bigint;
        maturity: bigint;
        state: bigint;
        bidCount: bigint;
        currentPass: bigint;
        settledRate: bigint;
        totalRepayment: bigint;
      }
    ],
    "view"
  >;

  getEncryptedRate: TypedContractMethod<
    [bondId: BigNumberish, bidIndex: BigNumberish],
    [string],
    "view"
  >;

  getWinners: TypedContractMethod<[bondId: BigNumberish], [string[]], "view">;

  hasBid: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isWinner: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  liquidate: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  nextBondId: TypedContractMethod<[], [bigint], "view">;

  publishResults: TypedContractMethod<
    [
      bondId: BigNumberish,
      clearingRate: BigNumberish,
      rateSignature: BytesLike,
      winnerFlags: boolean[],
      flagSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  repay: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  resolvePass: TypedContractMethod<
    [bondId: BigNumberish],
    [void],
    "nonpayable"
  >;

  revealForCompliance: TypedContractMethod<
    [bondId: BigNumberish, regulator: AddressLike],
    [void],
    "nonpayable"
  >;

  settle: TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;

  submitRate: TypedContractMethod<
    [bondId: BigNumberish, encRate: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bonds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        borrower: string;
        collateralToken: string;
        collateralAmount: bigint;
        borrowToken: string;
        slotSize: bigint;
        slotCount: bigint;
        maxRate: bigint;
        duration: bigint;
        biddingDeadline: bigint;
        maturity: bigint;
        minBidders: bigint;
        state: bigint;
        bidCount: bigint;
        currentPass: bigint;
        clearingRate: string;
        settledRate: bigint;
        totalRepayment: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBond"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCollateral"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeBond"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "complianceAccess"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBond"
  ): TypedContractMethod<
    [
      collateralToken: AddressLike,
      collateralAmount: BigNumberish,
      borrowToken: AddressLike,
      slotSize: BigNumberish,
      slotCount: BigNumberish,
      maxRate: BigNumberish,
      duration: BigNumberish,
      biddingDuration: BigNumberish,
      minBidders: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBidCount"
  ): TypedContractMethod<[bondId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBidder"
  ): TypedContractMethod<
    [bondId: BigNumberish, bidIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBond"
  ): TypedContractMethod<
    [bondId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        borrower: string;
        collateralToken: string;
        collateralAmount: bigint;
        borrowToken: string;
        slotSize: bigint;
        slotCount: bigint;
        maxRate: bigint;
        duration: bigint;
        biddingDeadline: bigint;
        maturity: bigint;
        state: bigint;
        bidCount: bigint;
        currentPass: bigint;
        settledRate: bigint;
        totalRepayment: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedRate"
  ): TypedContractMethod<
    [bondId: BigNumberish, bidIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinners"
  ): TypedContractMethod<[bondId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasBid"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWinner"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextBondId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishResults"
  ): TypedContractMethod<
    [
      bondId: BigNumberish,
      clearingRate: BigNumberish,
      rateSignature: BytesLike,
      winnerFlags: boolean[],
      flagSignatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolvePass"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealForCompliance"
  ): TypedContractMethod<
    [bondId: BigNumberish, regulator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[bondId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRate"
  ): TypedContractMethod<
    [bondId: BigNumberish, encRate: InEuint64Struct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BondCancelled"
  ): TypedContractEvent<
    BondCancelledEvent.InputTuple,
    BondCancelledEvent.OutputTuple,
    BondCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BondClosed"
  ): TypedContractEvent<
    BondClosedEvent.InputTuple,
    BondClosedEvent.OutputTuple,
    BondClosedEvent.OutputObject
  >;
  getEvent(
    key: "BondCreated"
  ): TypedContractEvent<
    BondCreatedEvent.InputTuple,
    BondCreatedEvent.OutputTuple,
    BondCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BondLiquidated"
  ): TypedContractEvent<
    BondLiquidatedEvent.InputTuple,
    BondLiquidatedEvent.OutputTuple,
    BondLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "BondRepaid"
  ): TypedContractEvent<
    BondRepaidEvent.InputTuple,
    BondRepaidEvent.OutputTuple,
    BondRepaidEvent.OutputObject
  >;
  getEvent(
    key: "BondResolved"
  ): TypedContractEvent<
    BondResolvedEvent.InputTuple,
    BondResolvedEvent.OutputTuple,
    BondResolvedEvent.OutputObject
  >;
  getEvent(
    key: "BondSettled"
  ): TypedContractEvent<
    BondSettledEvent.InputTuple,
    BondSettledEvent.OutputTuple,
    BondSettledEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceAccessGranted"
  ): TypedContractEvent<
    ComplianceAccessGrantedEvent.InputTuple,
    ComplianceAccessGrantedEvent.OutputTuple,
    ComplianceAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "LenderClaimed"
  ): TypedContractEvent<
    LenderClaimedEvent.InputTuple,
    LenderClaimedEvent.OutputTuple,
    LenderClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PassResolved"
  ): TypedContractEvent<
    PassResolvedEvent.InputTuple,
    PassResolvedEvent.OutputTuple,
    PassResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RateBidSubmitted"
  ): TypedContractEvent<
    RateBidSubmittedEvent.InputTuple,
    RateBidSubmittedEvent.OutputTuple,
    RateBidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;

  filters: {
    "BondCancelled(uint256,string)": TypedContractEvent<
      BondCancelledEvent.InputTuple,
      BondCancelledEvent.OutputTuple,
      BondCancelledEvent.OutputObject
    >;
    BondCancelled: TypedContractEvent<
      BondCancelledEvent.InputTuple,
      BondCancelledEvent.OutputTuple,
      BondCancelledEvent.OutputObject
    >;

    "BondClosed(uint256,bool)": TypedContractEvent<
      BondClosedEvent.InputTuple,
      BondClosedEvent.OutputTuple,
      BondClosedEvent.OutputObject
    >;
    BondClosed: TypedContractEvent<
      BondClosedEvent.InputTuple,
      BondClosedEvent.OutputTuple,
      BondClosedEvent.OutputObject
    >;

    "BondCreated(uint256,address,uint256,uint256,uint256,uint64,uint256,uint256)": TypedContractEvent<
      BondCreatedEvent.InputTuple,
      BondCreatedEvent.OutputTuple,
      BondCreatedEvent.OutputObject
    >;
    BondCreated: TypedContractEvent<
      BondCreatedEvent.InputTuple,
      BondCreatedEvent.OutputTuple,
      BondCreatedEvent.OutputObject
    >;

    "BondLiquidated(uint256)": TypedContractEvent<
      BondLiquidatedEvent.InputTuple,
      BondLiquidatedEvent.OutputTuple,
      BondLiquidatedEvent.OutputObject
    >;
    BondLiquidated: TypedContractEvent<
      BondLiquidatedEvent.InputTuple,
      BondLiquidatedEvent.OutputTuple,
      BondLiquidatedEvent.OutputObject
    >;

    "BondRepaid(uint256,uint256)": TypedContractEvent<
      BondRepaidEvent.InputTuple,
      BondRepaidEvent.OutputTuple,
      BondRepaidEvent.OutputObject
    >;
    BondRepaid: TypedContractEvent<
      BondRepaidEvent.InputTuple,
      BondRepaidEvent.OutputTuple,
      BondRepaidEvent.OutputObject
    >;

    "BondResolved(uint256)": TypedContractEvent<
      BondResolvedEvent.InputTuple,
      BondResolvedEvent.OutputTuple,
      BondResolvedEvent.OutputObject
    >;
    BondResolved: TypedContractEvent<
      BondResolvedEvent.InputTuple,
      BondResolvedEvent.OutputTuple,
      BondResolvedEvent.OutputObject
    >;

    "BondSettled(uint256,uint64,uint256)": TypedContractEvent<
      BondSettledEvent.InputTuple,
      BondSettledEvent.OutputTuple,
      BondSettledEvent.OutputObject
    >;
    BondSettled: TypedContractEvent<
      BondSettledEvent.InputTuple,
      BondSettledEvent.OutputTuple,
      BondSettledEvent.OutputObject
    >;

    "ComplianceAccessGranted(uint256,address,address)": TypedContractEvent<
      ComplianceAccessGrantedEvent.InputTuple,
      ComplianceAccessGrantedEvent.OutputTuple,
      ComplianceAccessGrantedEvent.OutputObject
    >;
    ComplianceAccessGranted: TypedContractEvent<
      ComplianceAccessGrantedEvent.InputTuple,
      ComplianceAccessGrantedEvent.OutputTuple,
      ComplianceAccessGrantedEvent.OutputObject
    >;

    "LenderClaimed(uint256,address,uint256)": TypedContractEvent<
      LenderClaimedEvent.InputTuple,
      LenderClaimedEvent.OutputTuple,
      LenderClaimedEvent.OutputObject
    >;
    LenderClaimed: TypedContractEvent<
      LenderClaimedEvent.InputTuple,
      LenderClaimedEvent.OutputTuple,
      LenderClaimedEvent.OutputObject
    >;

    "PassResolved(uint256,uint256)": TypedContractEvent<
      PassResolvedEvent.InputTuple,
      PassResolvedEvent.OutputTuple,
      PassResolvedEvent.OutputObject
    >;
    PassResolved: TypedContractEvent<
      PassResolvedEvent.InputTuple,
      PassResolvedEvent.OutputTuple,
      PassResolvedEvent.OutputObject
    >;

    "RateBidSubmitted(uint256,uint256,address)": TypedContractEvent<
      RateBidSubmittedEvent.InputTuple,
      RateBidSubmittedEvent.OutputTuple,
      RateBidSubmittedEvent.OutputObject
    >;
    RateBidSubmitted: TypedContractEvent<
      RateBidSubmittedEvent.InputTuple,
      RateBidSubmittedEvent.OutputTuple,
      RateBidSubmittedEvent.OutputObject
    >;

    "RefundClaimed(uint256,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
  };
}
